# Classes and Instances in Python

Ref: https://youtu.be/ZDa-Z5JzLYM

In [1]:
class Employee:
    tax_rate=0;
    def __init__(self,first,last,salary):
        self.first = first  # First name 
        self.last=last      # last name 
        self.salary=salary        # salary 
        self.email = first.lower()+'.'+last.lower()+'@gmail.com'
    # Function that will return the fullname of employee
    def fullname(self): 
        return '{} {}'.format(self.first,self.last)
    # Function that will ask the user for the tax rate return the amount of tax that employee need to pay
    def tax(self,tax_rate=0):
        tex_pay = self.salary*tax_rate
        return round(tex_pay,2)

In [2]:
emp_1 = Employee('Isaac','Newton',5500)
emp_2 = Employee('Albert','Einstein',5800)

In [3]:
tax_rate = 7/100 # 7% tax rate
print('Tax payment at 7%: '+str(emp_1.tax(tax_rate)))
# 0% tax rate when the user does not declare
print('Tax payment: '+str(emp_1.tax()))

Tax payment at 7%: 385.0
Tax payment: 0


<span style="color:blue">Example for vector variables</span>  

In [4]:
import numpy as np
class Vectors:
    v3=np.array([0,0]) # set a defult vector for v3 to [0,0]
    def __init__(self,v1,v2,v3=v3):
        self.v1=v1
        self.v2=v2
        self.v3=v3 # This vector has a defult vector [0,0]

In [5]:
v_1=np.array([1,2])
v_2=np.array([3,5])
vec_0 = Vectors(v_1,v_2)

In [6]:
vec_0.v1

array([1, 2])

In [7]:
vec_0.v2

array([3, 5])

In [8]:
vec_0.v3

array([0, 0])

In [9]:
vec_0.v3=np.array([8,8])
vec_0.v3

array([8, 8])

In [10]:
vec_0.v3+vec_0.v1

array([ 9, 10])